spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blockchain_manager?autoReconnect=true&useUnicode=true&useSSL=false
    password: 12345678
    username: root